# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: "echo Hello ${ENV_VAR_NAME} "
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: "echo World! ${MY_VAR}"
  save_hello_world_output:
    docker:
      - image: cimg/base:2023.02
    steps:
      - run:
          command: |
            echo Hello World > /tmp/output.txt
            ls -la /tmp
            ls -la .
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:2023.02
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          command: |
            ls -la /tmp
            ls -la .
            cat /tmp/output.txt
    
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
