version: 2.1

commands:
  print_pipeline_id:
    parameters:
      to:
        type: string
        default: "/tmp/output.txt"  
    steps:
      - run:
          command: |
            echo $CIRCLE_WORKFLOW_ID > << parameters.to >>

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2023.02
    steps:
      - run:
          command: |
            echo Hello World > /tmp/output.txt
      - print_pipeline_id:
          to: "/tmp/pipeline_id.txt"
      - persist_to_workspace:
          root: /tmp
          paths:
            - pipeline_id.txt
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:2023.02
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          command: |
            ls -la /tmp
            ls -la .
            cat /tmp/output.txt
            cat /tmp/pipeline_id.txt
            exit 1
      - run:
          name: Upload Failed Tests
          command: |
            echo "Hello Error!"
          when: on_fail
    
workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
